#!/bin/sh

# snmp plugin Gude Expert Power Control 8220 Serie
# (C) Vincent Kocher <vkocher@kozo.ch>
# 08.10.2019 
# Version 0.01

# what is a Gudo Power Control
#====================================
# The Gude PowerControl has two Main Powerinput and each of them 6 switchable Output
# Only the two Power Input is Power Monitored
# the Powercontrol has Web access and the main part looks like this:
# https://wombat3.kozo.ch/j/images/content/2018/08/epc8220.PNG
# http://wiki.gude.info/FAQ_EPC_SNMP_Engl

# How i do use the Gudo Power Control
#====================================
# MainPower Input to B
# B.1 Power Output to UPC
# UPC Output to Gude Powercontrol Input A
# So B will Monitor all the Power used
#    A will only show what the UPC Supported device use
# UPC supported device would be like EdgeRouter, Firewall, DMZ-Switch, Main Server (with Bind, Mail, Web)

# Coal of the Plugin
# Monitoring the Powerconsumption of the Network/Server in a Rack 

# ==============================================================================
# MIB Variablen used
# to MIB Variable values used and type
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# Device Name 
# snmpwalk -v 2c -c public 10.147.42.31 1.3.6.1.2.1.1.1.0  | awk '{print $4,$5,$6,$7}'
#
# Power Active in "W" ( i will call it APA and BPA)
# A | snmpwalk -v 2c -c public 10.147.42.31 1.3.6.1.4.1.28507.38.1.5.1.2.1.4.1 | awk '{print $4,$5,$6,$7}'
# B | snmpwalk -v 2c -c public 10.147.42.31 1.3.6.1.4.1.28507.38.1.5.1.2.1.4.2 | awk '{print $4,$5,$6,$7}'

# Total Energie Active in "kWh" (is fix and just goes Up):
# A | snmpwalk -v 2c -c public 10.147.42.31 1.3.6.1.4.1.28507.38.1.5.1.2.1.18.1 | awk '{print $4,$5,$6,$7}'
# B | snmpwalk -v 2c -c public 10.147.42.31 1.3.6.1.4.1.28507.38.1.5.1.2.1.18.2 | awk '{print $4,$5,$6,$7}'

# Total Energie Active in "kWh" (goes up but could be reseted):
# A | snmpwalk -v 2c -c public 10.147.42.31 1.3.6.1.4.1.28507.38.1.5.1.2.1.18.1 | awk '{print $4,$5,$6,$7}'
# B | snmpwalk -v 2c -c public 10.147.42.31 1.3.6.1.4.1.28507.38.1.5.1.2.1.18.2 | awk '{print $4,$5,$6,$7}'

# Current AC rms
# A | snmpwalk -v 2c -c public 10.147.42.31 1.3.6.1.4.1.28507.38.1.5.1.2.1.5.1 | awk '{print $4,$5,$6,$7}'
# B | snmpwalk -v 2c -c public 10.147.42.31 1.3.6.1.4.1.28507.38.1.5.1.2.1.5.2 | awk '{print $4,$5,$6,$7}'

# DEVICENAME="/usr/bin/snmpget -v 2c -c public 10.147.42.31 1.3.6.1.4.1.28507.38.1.5.1.2.1.5.2 | awk '{print $4,$5,$6,$7}'"

# ================================================================================
# Variable definition ...
# ================================================================================

CLIENTIP="10.147.42.31"
COMMUNITY="public"
VERSION="2c"
POWERPREISkWh="0.1624"
DEVICENAME="/usr/bin/snmpget -v $VERSION -c $COMMUNITY $CLIENTIP 1.3.6.1.2.1.1.1.0 | awk '{print $4,$5,$6,$7}'"




# ================================================================================
# the code to run...
# ================================================================================


MIB=/usr/share/snmp/mibs/GUDEADS-EPC822X-MIB.txt
graph_period="second"
SNMPCLIENT=`basename $0 | sed 's/^snmp_//g' | cut -d "_" -f1`
SNMPGET="/usr/bin/snmpget -m $MIB -v2 -c $COMMUNITY $SNMPCLIENT"

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "suggest" ]; then
	# This part does not work well
	# the pinf command must support broadcasts
	# echo  | nc -u -w 1 192.168.5.0 8513
	#
	# 1.) find all network devices
	# 2.) find out if it reacts to a UDP package at port 8513
	# 3.) find out if it is a W & T WebGraph
	IPS=`ping -b -c2  $BROADCAST | grep icmp 2> /dev/null | sed s/.*from//g | cut -f1 -d":"`
	for IP in $IPS ; do
		unset RETURN
		RETURN=`echo "-" | nc -u -w 1 $IP 8513`
		RETURN=foo
		if [ "$RETURN" ] ; then
			/usr/bin/snmpget -m $MIB -v1 -c $COMMUNITY $IP WebGraph-2xThermometer-MIB::wtWebioAn2GraphSensors.0 > /dev/null 2>&1
			RC=$?
			RC=0
			if [ ! "$RC" != "0" ] ; then
				FILE=`basename $0`
				DIR=`dirname $0`
				HOSTNAME=`host $IP | sed s/.*pointer//\ `
				HOSTNAME=`echo $HOSTNAME | sed -e 's/\.$//'`
				LINKDIR="/etc/munin/plugins/"
				LINKFILE=`echo $FILE | sed s/__/_$HOSTNAME_/`
				echo file $FILE dir $DIR hostname $HOSTNAME linkdir $LINKDIR	linkfile $LINKFILE
				#echo "ln -s $DIR/$FILE $LINKNAME"
			fi

			unset SNMPCLIENT
		fi
	done
	exit

fi

if [ "$1" = "config" ]; then

	# some fix values
        echo "host_name $SNMPCLIENT"
        echo 'graph_category Power'
        echo 'graph_args --base 1000 -l 0'

	# some variables, fetched from the device
	GRAPH_TITLE=`$SNMPGET WebGraph-2xThermometer-MIB::wtWebioAn2GraphDeviceName.0 | sed s/.*STRING:// | sed s/\"//g`
	GRAPH_INFO=`$SNMPGET WebGraph-2xThermometer-MIB::wtWebioAn2GraphDeviceText.0 | sed s/.*STRING:// | sed s/\"//g`
	GRAPH_VLABEL=`$SNMPGET WebGraph-2xThermometer-MIB::wtWebioAn2GraphDeviceLocation.0 | sed s/.*STRING:// | sed s/\"//g`
	SENSOR_1_LABEL=`$SNMPGET WebGraph-2xThermometer-MIB::wtWebioAn2GraphPortName.1 | sed s/.*STRING:// | sed s/\"//g`
	SENSOR_2_LABEL=`$SNMPGET WebGraph-2xThermometer-MIB::wtWebioAn2GraphPortName.2 | sed s/.*STRING:// | sed s/\"//g`
	SENSOR_1_CRITICAL=`$SNMPGET WebGraph-2xThermometer-MIB::wtWebioAn2GraphAlarmMax.1 | sed s/.*STRING:// | sed s/\"//g`
	SENSOR_2_CRITICAL=`$SNMPGET WebGraph-2xThermometer-MIB::wtWebioAn2GraphAlarmMax.2 | sed s/.*STRING:// | sed s/\"//g`

	# echo the result to munin
	echo "graph_title $GRAPH_TITLE" 
        echo "graph_info $GRAPH_INFO"
        echo "graph_vlabel $GRAPH_VLABEL"
        echo "Sensor_1.label $SENSOR_1_LABEL"
	echo "Sensor_2.label $SENSOR_2_LABEL"
	echo "Sensor_1.critical $SENSOR_1_CRITICAL"
	echo "Sensor_2.critical $SENSOR_2_CRITICAL"
        echo 'Sensor_1.min 0'
        echo 'Sensor_2.min 0'
        echo 'Sensor_1.graph  yes'
        echo 'Sensor_2.graph yes'
else

	Sensor_1=`$SNMPGET WebGraph-2xThermometer-MIB::wtWebioAn2GraphTempValue.1 | sed s/.*STRING:// | sed s/\"//g | sed s/,/./`
	Sensor_2=`$SNMPGET WebGraph-2xThermometer-MIB::wtWebioAn2GraphTempValue.2 | sed s/.*STRING:// | sed s/\"//g | sed s/,/./`
	echo Sensor_1.value $Sensor_1
	echo Sensor_2.value $Sensor_2
fi

# Source of the file is:
# snmp plugin for Wiesemann und Thies WebThermometer
# (C) Michael Renner <michael.renner@gmx.de>
# 10.07.2007
# Version 0.2
